### ISSUE TITLE
First example is missing a 'agent.next' call

### ISSUE THREAD

**Issue by clupprich** [indexzero/http-agent#1]
I didn't want to fork the repository just for a single missing line in the example in the readme: In the 'next' event listener, there's a line missing, it should be

```
agent.addListener('next', function (e, agent) {
    // Simple usage: Just output the raw
    // HTML returned from each request
    sys.puts(agent.body);
    agent.next();
});
```

Edit: It's missing in all examples in the readme. Am I doing something wrong?

**Comment by indexzero** [comment]
Thanks. Fixed and committed.
