### ISSUE TITLE
Setting the Headers 

### ISSUE THREAD

**Issue by level09** [indexzero/http-agent#5]
How to set the user agent ? most websites will block the request if no user agent is defined, I tried the following : 

var userAgent = 'Googlebot/2.1 (http://www.googlebot.com/bot.html'; 

var url = 'google.com'

var options = [{uri: '',headers:{'user-agent':userAgent}},{uri:'news',headers:{'user-agent':userAgent}}];

doesn't seem to work.

**Comment by level09** [comment]
I have forked the repo and added a default header, so the agent won't be blocked.

**Comment by indexzero** [comment]
@level09 Thanks. I would've assumed the usage you supplied would have worked. I wrote this project ~1 year ago. I'm digging in now to give it some love.

**Comment by indexzero** [comment]
@level09 Can you try this again in 0.1.2? It should work. Some additional test coverage would be awesome. Also, I would accept a pull request setting the default `User-Agent` header. I strongly urge that you pull from the new `0.1.2` codebase though, it has been significantly refactored internally.

See: b877b7c9bc8e0c5da443428e8f11aec8fe565277 and 06c228eb9ba663f89911bd562bd1bc90107d5a31
